on:
  push:
    branches:
      - main
      
  workflow_dispatch:
  
jobs:
  run-tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0
      - name: Enable yarn
        run: corepack enable
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test


  
  
